
export const products = [
  {
    categoryId: null,
    name: 'Гарнитура Cooler Master CH331 USB',
    description: 'cooler_master_ch331_usb',
    article: 'А066242',
    image: '/ch331.png',
    price: 1999,
    quantityAvailable: 15,
    discount: 15,
    isChecked: false,
    isBestseller: true,
    bonuses: 5,
    rating: 4.7,
    reviewAmount: 12,
  },
  {
    categoryId: null,
    name: 'Гарнитура Cooler Master CH331 USB',
    description: 'cooler_master_ch331_usb',
    article: 'А066242',
    image: '/ch331.png',
    price: 1999,
    quantityAvailable: 15,
    discount: 15,
    isChecked: false,
    isBestseller: true,
    bonuses: 5,
    rating: 4.7,
    reviewAmount: 12,
  },{
    categoryId: null,
    name: 'Гарнитура Cooler Master CH331 USB',
    description: 'cooler_master_ch331_usb',
    article: 'А066242',
    image: '/ch331.png',
    price: 1999,
    quantityAvailable: 15,
    discount: 15,
    isChecked: false,
    isBestseller: true,
    bonuses: 5,
    rating: 4.7,
    reviewAmount: 12,
  },{
    categoryId: null,
    name: 'Гарнитура Cooler Master CH331 USB',
    description: 'cooler_master_ch331_usb',
    article: 'А066242',
    image: '/ch331.png',
    price: 1999,
    quantityAvailable: 15,
    discount: 15,
    isChecked: false,
    isBestseller: true,
    bonuses: 5,
    rating: 4.7,
    reviewAmount: 12,
  },{
    categoryId: null,
    name: 'Гарнитура Cooler Master CH331 USB',
    description: 'cooler_master_ch331_usb',
    article: 'А066242',
    image: '/ch331.png',
    price: 1999,
    quantityAvailable: 15,
    discount: 15,
    isChecked: false,
    isBestseller: true,
    bonuses: 5,
    rating: 4.7,
    reviewAmount: 12,
  },{
    categoryId: null,
    name: 'Гарнитура Cooler Master CH331 USB',
    description: 'cooler_master_ch331_usb',
    article: 'А066242',
    image: '/ch331.png',
    price: 1999,
    quantityAvailable: 15,
    discount: 15,
    isChecked: false,
    isBestseller: true,
    bonuses: 5,
    rating: 4.7,
    reviewAmount: 12,
  },{
    categoryId: null,
    name: 'Гарнитура Cooler Master CH331 USB',
    description: 'cooler_master_ch331_usb',
    article: 'А066242',
    image: '/ch331.png',
    price: 1999,
    quantityAvailable: 15,
    discount: 15,
    isChecked: false,
    isBestseller: true,
    bonuses: 5,
    rating: 4.7,
    reviewAmount: 12,
  },
]